-- ---------------------------------------------------------------------------
-- jq_game
--   status is an inline check; a lookup table would allow runtime extension
--   but adds a join to every query — the check constraint is simpler here.
-- ---------------------------------------------------------------------------
create table jq_game (
  game_id             number generated by default on null as identity,
  title               varchar2(100 char)  not null,
  status              varchar2(12 char)   default 'SETUP' not null,
  current_question_id number,                             -- FK added via ALTER below after jq_question exists
  started_at_ts       timestamp,
  finished_at_ts      timestamp,
  constraint pk_jq_game        primary key (game_id),
  constraint ck_jq_game_status check (status in ('SETUP', 'RUNNING', 'FINISHED'))
);

-- ---------------------------------------------------------------------------
-- jq_candidate
-- ---------------------------------------------------------------------------
create table jq_candidate (
  candidate_id  number generated by default on null as identity,
  display_name  varchar2(80 char) not null,
  created_at_ts timestamp default systimestamp not null,
  constraint pk_jq_candidate      primary key (candidate_id),
  constraint uq_jq_candidate_name unique (display_name)
);

-- ---------------------------------------------------------------------------
-- jq_game_candidate
--   locked_out: Oracle SQL has no boolean type before 23c; char(1) Y/N is
--   the conventional substitute.  A check constraint enforces the domain.
--   seat_no upper bound is 99 — enough for any realistic classroom session.
-- ---------------------------------------------------------------------------
create table jq_game_candidate (
  game_id      number       not null,
  candidate_id number       not null,
  seat_no      number(2)    not null,
  score        number       default 0   not null,
  locked_out   char(1 char) default 'N' not null,
  constraint pk_jq_game_candidate primary key (game_id, candidate_id),
  constraint fk_jq_gc_game        foreign key (game_id)      references jq_game      (game_id),
  constraint fk_jq_gc_candidate   foreign key (candidate_id) references jq_candidate (candidate_id),
  constraint uq_jq_gc_seat        unique (game_id, seat_no),
  constraint ck_jq_gc_locked      check (locked_out in ('Y', 'N')),
  constraint ck_jq_gc_seat        check (seat_no between 1 and 99)
);

-- ---------------------------------------------------------------------------
-- jq_category  (lookup)
-- ---------------------------------------------------------------------------
create table jq_category (
  category_id   number generated by default on null as identity,
  category_name varchar2(80 char) not null,
  constraint pk_jq_category      primary key (category_id),
  constraint uq_jq_category_name unique (category_name)
);

-- ---------------------------------------------------------------------------
-- jq_point_level  (lookup)
--   Defines which point values are legal per round.
--   Round 1: 100-500.  Round 2: 200-1000.
-- ---------------------------------------------------------------------------
create table jq_point_level (
  round_no    number(1)      not null,
  point_value number(4)      not null,
  level_label varchar2(40 char) not null,
  constraint pk_jq_point_level       primary key (round_no, point_value),
  constraint uq_jq_point_level_label unique (level_label),
  constraint ck_jq_point_level_slot  check (
    (round_no = 1 and point_value in (100, 200, 300, 400, 500))
    or
    (round_no = 2 and point_value in (200, 400, 600, 800, 1000))
  )
);

-- ---------------------------------------------------------------------------
-- jq_question
--   clue_text + four fixed options reflect the multiple-choice format.
--   is_daily_double: char(1) Y/N — same boolean convention as locked_out.
--   used_in_game_id: set when the question is selected for a game, preventing
--   the same question from appearing in two games.
-- ---------------------------------------------------------------------------
create table jq_question (
  question_id     number generated by default on null as identity,
  category_id     number            not null,
  clue_text       varchar2(500 char) not null,
  option_a        varchar2(200 char) not null,
  option_b        varchar2(200 char) not null,
  option_c        varchar2(200 char) not null,
  option_d        varchar2(200 char) not null,
  correct_option  char(1 char)      not null,
  point_value     number(4)         not null,
  round_no        number(1)         default 1 not null,
  is_daily_double char(1 char)      default 'N' not null,
  used_in_game_id number,
  constraint pk_jq_question          primary key (question_id),
  constraint fk_jq_question_category foreign key (category_id)
    references jq_category  (category_id),
  constraint fk_jq_question_level    foreign key (round_no, point_value)
    references jq_point_level (round_no, point_value),
  constraint fk_jq_question_game     foreign key (used_in_game_id)
    references jq_game (game_id),
  constraint uq_jq_question_slot     unique (category_id, round_no, point_value),
  constraint ck_jq_question_correct  check (correct_option  in ('A', 'B', 'C', 'D')),
  constraint ck_jq_question_slot     check (
    (round_no = 1 and point_value in (100, 200, 300, 400, 500))
    or
    (round_no = 2 and point_value in (200, 400, 600, 800, 1000))
  ),
  constraint ck_jq_question_daily    check (is_daily_double in ('Y', 'N'))
);

-- jq_game.current_question_id references jq_question, so the FK is added
-- after jq_question exists.
alter table jq_game add constraint fk_jq_game_current_question
  foreign key (current_question_id) references jq_question (question_id);

-- ---------------------------------------------------------------------------
-- jq_joker_type  (lookup)
-- ---------------------------------------------------------------------------
create table jq_joker_type (
  joker_code  varchar2(10 char)   not null,
  description varchar2(200 char)  not null,
  constraint pk_jq_joker_type primary key (joker_code)
);

-- ---------------------------------------------------------------------------
-- jq_candidate_joker
--   One row per (game, candidate, joker) allocated at game setup.
--   used_at and used_on_question_id are either both null (unused) or both
--   not null (used).  The pair check constraint enforces this invariant.
-- ---------------------------------------------------------------------------
create table jq_candidate_joker (
  game_id            number            not null,
  candidate_id       number            not null,
  joker_code         varchar2(10 char) not null,
  used_on_question_id number,
  used_at            timestamp,
  constraint pk_jq_candidate_joker primary key (game_id, candidate_id, joker_code),
  constraint fk_jq_cj_gc          foreign key (game_id, candidate_id)
    references jq_game_candidate (game_id, candidate_id),
  constraint fk_jq_cj_joker       foreign key (joker_code)
    references jq_joker_type (joker_code),
  constraint fk_jq_cj_question    foreign key (used_on_question_id)
    references jq_question (question_id),
  constraint ck_jq_cj_used_pair   check (
    (used_at is null     and used_on_question_id is null)
    or
    (used_at is not null and used_on_question_id is not null)
  )
);

-- ---------------------------------------------------------------------------
-- jq_buzz
--   Records every button press for a question.  reaction_ms is the elapsed
--   time from question reveal to buzz; ties are broken by buzzed_at then
--   buzz_id.  is_valid is set to N when a candidate answers incorrectly,
--   allowing the next-fastest valid buzz to answer.
-- ---------------------------------------------------------------------------
create table jq_buzz (
  buzz_id      number generated by default on null as identity,
  game_id      number       not null,
  question_id  number       not null,
  candidate_id number       not null,
  buzzed_at    timestamp    default systimestamp not null,
  reaction_ms  number(6)    not null,
  is_valid     char(1 char) default 'Y' not null,
  constraint pk_jq_buzz          primary key (buzz_id),
  constraint fk_jq_buzz_gc       foreign key (game_id, candidate_id)
    references jq_game_candidate (game_id, candidate_id),
  constraint fk_jq_buzz_question foreign key (question_id)
    references jq_question (question_id),
  constraint uq_jq_buzz_once     unique (game_id, question_id, candidate_id),
  constraint ck_jq_buzz_reaction check (reaction_ms between 0 and 999999),
  constraint ck_jq_buzz_valid    check (is_valid in ('Y', 'N'))
);

-- ---------------------------------------------------------------------------
-- jq_answer
--   One row per candidate per question; records the chosen option, whether
--   it was correct, and the resulting score change.  answered_at captures
--   the moment the answer was submitted, which may differ from buzzed_at.
-- ---------------------------------------------------------------------------
create table jq_answer (
  answer_id       number generated by default on null as identity,
  game_id         number       not null,
  question_id     number       not null,
  candidate_id    number       not null,
  selected_option char(1 char) not null,
  is_correct      char(1 char) not null,
  score_delta     number       not null,
  answered_at     timestamp    default systimestamp not null,
  constraint pk_jq_answer          primary key (answer_id),
  constraint fk_jq_answer_gc       foreign key (game_id, candidate_id)
    references jq_game_candidate (game_id, candidate_id),
  constraint fk_jq_answer_question foreign key (question_id)
    references jq_question (question_id),
  constraint uq_jq_answer_once     unique (game_id, question_id, candidate_id),
  constraint ck_jq_answer_option   check (selected_option in ('A', 'B', 'C', 'D')),
  constraint ck_jq_answer_correct  check (is_correct      in ('Y', 'N'))
);

-- ---------------------------------------------------------------------------
-- jq_game_event  (audit / event log)
-- ---------------------------------------------------------------------------
create table jq_game_event (
  event_id   number generated by default on null as identity,
  game_id    number            not null,
  event_type varchar2(40 char) not null,
  details    varchar2(1000 char),
  created_at timestamp         default systimestamp not null,
  constraint pk_jq_game_event  primary key (event_id),
  constraint fk_jq_event_game  foreign key (game_id) references jq_game (game_id)
);

-- ---------------------------------------------------------------------------
-- Indexes
--   ix_jq_event_game   : speeds up retrieving the event log for a single game
--                        in chronological order (the most common display query).
--   ix_jq_answer_question: supports per-question answer lookups used when
--                        checking whether a candidate already answered and
--                        when aggregating results after a question closes.
--   ix_jq_buzz_fastest : the critical hot path — finding the fastest valid
--                        buzz for the current question uses all four columns:
--                        game_id + question_id to scope the question,
--                        is_valid to filter out invalidated buzzes, and
--                        reaction_ms to sort for the winner.
-- ---------------------------------------------------------------------------
create index ix_jq_event_game      on jq_game_event (game_id, created_at);
create index ix_jq_answer_question on jq_answer     (game_id, question_id);
create index ix_jq_buzz_fastest    on jq_buzz       (game_id, question_id, is_valid, reaction_ms);
